Repository rustyhorde/vergen, pull requests merged in 2024-01, with the labels that each got.

#275 Added struct_field_names to allow
  vergen-pretty/build.rs
  vergen-pretty/src/lib.rs
  vergen/build.rs
  vergen/src/lib.rs
Labels: lint

#277 Updated to sysinfo 0.30.4
  .gitignore
  vergen/Cargo.toml
  vergen/src/feature/si.rs
Labels: dependencies

#278 Updated to gix 0.57.1
  vergen/Cargo.toml
  vergen/src/utils.rs
  vergen/tests/git_output.rs
Labels: dependencies

#279 Moved renamed nightly lints
  vergen-pretty/src/lib.rs
  vergen/src/lib.rs
Labels: lint

#283 Complete implementation for VERGEN_GIT_DIRTY
  .github/workflows/main.yml
  Cargo.toml
  repo_util/Cargo.toml
  repo_util/build.rs
  repo_util/src/lib.rs
  repo_util/src/repo/mod.rs
  vergen-pretty/src/pretty/mod.rs
  vergen/Cargo.toml
  vergen/src/constants.rs
  vergen/src/emitter.rs
  vergen/src/feature/build.rs
  vergen/src/feature/git/cmd.rs
  vergen/src/feature/git/git2.rs
  vergen/src/feature/git/gix.rs
  vergen/src/key.rs
  vergen/src/lib.rs
  vergen/src/utils.rs
  vergen/tests/git_output.rs
Labels: enhancement

#284 version bump for next 'vergen' release
  vergen/Cargo.toml
  vergen/tests/git_output.rs
Labels: Release

#285 Remove commented out remove in drop for TestRepos
  repo_util/src/repo/mod.rs
Labels: bug, CI

#286 Update top-level docs with more relevant examples
  vergen/Cargo.toml
  vergen/src/lib.rs
Labels: documentation

#287 Add support for `RefreshKind` to the `sysinfo` feature
  vergen/Cargo.toml
  vergen/src/feature/si.rs
Labels: enhancement

#288 Add support for shallow clones
  repo_util/src/repo/mod.rs
  vergen/src/feature/git/cmd.rs
  vergen/src/feature/git/git2.rs
  vergen/src/feature/git/gix.rs
  vergen/tests/git_output.rs
Labels: enhancement

#289 Filter newlines from cargo instruction output
  vergen/src/emitter.rs
Labels: enhancement

#290 initial implementation of VERGEN_CARGO_DEPENDENCIES
  vergen/Cargo.toml
  vergen/src/constants.rs
  vergen/src/feature/cargo.rs
  vergen/src/key.rs
  vergen/src/lib.rs
  vergen/tests/cargo_output.rs
  vergen/tests/git_output.rs
Labels: enhancement

#291 re-export DependencyKind used in api
  vergen/src/lib.rs
Labels: enhancement

#292 version bump for next release
  vergen/Cargo.toml
Labels: Release

#293 Added two new outputs to vergen-pretty
  vergen-pretty/Cargo.toml
  vergen-pretty/src/lib.rs
Labels: enhancement

#294 cargo feature unification support
  .github/workflows/main.yml
  README.md
  run_all.fish
  vergen/Cargo.toml
  vergen/src/feature/git/mod.rs
  vergen/src/lib.rs
  vergen/tests/git_output.rs
Labels: enhancement

#296 Removed one more backtick, version bump
  README.md
  vergen/Cargo.toml
  vergen/src/lib.rs
Labels: documentation

#298 Fix incorrect docs
  README.md
  vergen/src/lib.rs
Labels: documentation

#303 Add action to upload static coverage content to Pages
  .github/workflows/static.yml
Labels: enhancement, documentation

#305 Version 9 Beta 1
  MIGRATING_v8_to_v9.md
  README.md
  vergen-git2/Cargo.toml
  vergen-git2/src/lib.rs
  vergen-gitcl/Cargo.toml
  vergen-gitcl/src/lib.rs
  vergen-gix/Cargo.toml
  vergen-gix/src/lib.rs
  vergen-lib/Cargo.toml
  vergen-lib/src/keys.rs
  vergen-pretty/Cargo.toml
  vergen-pretty/build.rs
  vergen-pretty/src/lib.rs
  vergen-pretty/src/pretty/mod.rs
  vergen-pretty/src/utils.rs
  vergen/Cargo.toml
  vergen/src/lib.rs
Labels: enhancement, documentation

#306 Version 9 Beta 2
  README.md
  vergen-pretty/Cargo.toml
  vergen-pretty/build.rs
  vergen-pretty/src/lib.rs
Labels: enhancement, documentation
